### ISSUE TITLE
Feature Request: Provide a means of querying quota

### ISSUE THREAD

**Issue by machawk1** [ukwa/ukwa-gsheets-utils#2]
For a large number of requests, as mentioned in the README, a user may hit the quota ceiling. It would be useful to allow this value to be queried and displayed in a cell to give more insight as to why bulk querying is failing at a certain point in a list of URIs.

**Comment by anjackson** [comment]
FWIW I thought the error it gives when you hit the quota was pretty clear. Admittedly you do need to inspect the cell to see it.

Querying the quota would be a good option but I have no idea how to do that. Haven't found an API for it yet.

**Comment by anjackson** [comment]
There doesn't seem to be any way to check the quota.  The most sensible route is to modify the operation so we can batch up multiple requests and perhaps cache the results, to make it much less likely the limit will be hit.
